apiVersion: apps/v1
kind: Deployment
metadata: 
  name: webapp
  labels:
    app: aspnet-core-mvc
spec:
  replicas: 1
  selector:
    matchLabels:
      service: webapp
  template:
    metadata:
      labels:
        app: aspnet-core-mvc
        service: webapp
    spec:
      containers:
        - name: webapp
          image: blacktelescope.azurecr.io/pompom:246983b3dae71803289c826e75720300cf601d56
          resources:
            requests:
                cpu: "250m"
                memory: "512Mi"
            limits:
                cpu: "500m"
                memory: "1Gi"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
