apiVersion: v1
kind: Service
metadata:
  name: webapp
  labels:
    app: aspnet-core-mvc
    service: webapp
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: ranchu
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    service: webapp